version: 2
jobs:
  pushData:
    docker:
      - image: circleci/python:3
    working_directory: ~/project
    environment:
      BASH_ENV: BASH_ENV
    steps:
      # add checkout to add github.com to known hosts
      - checkout
      - add_ssh_keys
      - attach_workspace:
          at: ~/project/
      - run:
          name: clone data repo
          command: git clone git@github.com:mathewmeconry/TV7_EPG_Data.git 
      - run:
          name: move files
          command: |
            mv tv7_epg.xml TV7_EPG_Data/
            mv tv7_teleboy_epg.xml TV7_EPG_Data/
      - run:
          name: configure git
          command: | 
            cd TV7_EPG_Data/
            git config user.email "automated@circleci.com"
            git config user.name "CircleCI"
      - run:
          name: compress files 
          command: |
            cd TV7_EPG_Data/
            gzip -f tv7_epg.xml
            gzip -f tv7_teleboy_epg.xml
      - run:
          name: push stuff
          command: |
            cd TV7_EPG_Data/
            git add .
            git commit -m "`date`"
            git push
  parse:
    docker:
      - image: circleci/python:3
    working_directory: ~/project
    environment:
      BASH_ENV: BASH_ENV
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: python3 -m pip install --user -r requirements.txt
      - run:
          name: update $PATH
          command: export PATH="$PATH:~/.local/bin"
      - run:
          name: run parser
          command: python3 main.py    
          no_output_timeout: 2h
      - persist_to_workspace:
          root: .
          paths:
            - ./tv7_epg.xml
            - ./tv7_teleboy_epg.xml

workflows:
  version: 2
  commit:
    jobs: 
      - parse:
          filters:
            branches:
              only:
                - master
      - pushData:
          requires:
            - parse
  cron:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - parse
        - pushData:
            requires:
              - parse
  